src/Entity/FactureDetail.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FactureDetailRepository")
 */
class FactureDetail
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Facture", inversedBy="factureDetails")
     */
    private $Facture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PU;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Qtt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ReferenceDet;


    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $MontantTva;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tva", inversedBy="factureDetails")
     */
    private $Tva;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFacture(): ?Facture
    {
        return $this->Facture;
    }

    public function setFacture(?Facture $Facture): self
    {
        $this->Facture = $Facture;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(?string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getPU(): ?float
    {
        return $this->PU;
    }

    public function setPU(?float $PU): self
    {
        $this->PU = $PU;

        return $this;
    }

    public function getQtt(): ?float
    {
        return $this->Qtt;
    }

    public function setQtt(?float $Qtt): self
    {
        $this->Qtt = $Qtt;

        return $this;
    }

    public function getReferenceDet(): ?string
    {
        return $this->ReferenceDet;
    }

    public function setReferenceDet(?string $ReferenceDet): self
    {
        $this->ReferenceDet = $ReferenceDet;

        return $this;
    }

    public function getMontantTva(): ?float
    {
        return $this->MontantTva;
    }

    public function setMontantTva(?float $MontantTva): self
    {
        $this->MontantTva = $MontantTva;

        return $this;
    }

    public function getTva(): ?Tva
    {
        return $this->Tva;
    }

    public function setTva(?Tva $Tva): self
    {
        $this->Tva = $Tva;

        return $this;
    }

}

templates/extra/macros/helper_facture.html.twig
{% macro header(isAssujeti) %}

    <thead>
    <tr>
        <th class="text-left th-header">Réf.</th>
        <th class="text-left th-header border-left-white">Désignation</th>
        <th class="text-center th-header border-left-white" width="80">Qté</th>
        <th class="text-center th-header border-left-white" width="80">P.U. HT</th>
        {% if isAssujeti %}
            <th class="text-center th-header border-left-white" width="80">Tva</th>
        {% endif %}
        <th class="text-center th-header border-left-white" width="80">Total HT</th>
    </tr>
    </thead>
{% endmacro %}

{% macro footer(isAssujeti , total , type ) %}

    {% set type_title = " SOUS TOTAL HT" %}

    <tfoot>
    {% if isAssujeti %}
    <tr>
        <td colspan="2"></td>
        <td class="border-bottom-black" colspan="3">{{type_title}}</td>
        <td class="border-bottom-black">{{ prettyPrices(total)|raw }}</td>
    </tr>
    {% else %}
    <tr>
        <td colspan="2"></td>
        <td class="border-bottom-black" colspan="2">{{type_title}}</td>
        <td class="border-bottom-black">{{ prettyPrices(total)|raw }}</td>
    </tr>
    {% endif %}
    </tfoot>
{% endmacro %}

{% macro corps(facturation , isAssujeti ) %}
    {% set total =  facturation.qtt * facturation.pu %}
<tr>
    <td class="text-left bg-grey-dark"><h3>{{ facturation.referenceDet }}</h3></td>
    <td class="text-left bg-grey"><h3>{{ facturation.libelle }}</h3></td>
    <td class="text-center bg-grey-dark">{{ facturation.qtt }}</td>
    <td class="text-right bg-grey">{{ prettyPrices(facturation.pu)|raw }}</td>
    {% if isAssujeti %}
        <td class="text-right bg-grey-dark"><strong>{{ facturation.Tva?facturation.Tva.Taux:'-' }} %</strong></td>
    {%endif %}
    <td class="text-right {% if isAssujeti %}bg-grey{% else %}bg-grey-dark{% endif %}">{{ prettyPrices(total)|raw }}</td>
    </tr>
{% endmacro %}

templates/extra/macros/shortcut.html.twig
{% macro badge_bool(item) %}
    {% if(item) %}
        <div class="chip chip-success">
            <div class="chip-body">
                <div class="chip-text">OUI</div>
            </div>
        </div>
    {% else %}

        <div class="chip chip-danger">
            <div class="chip-body">
                <div class="chip-text">NON</div>
            </div>
        </div>
    {% endif %}
{% endmacro %}

{% macro big_loader() %}
    <div id="page_loader" class="in">
        <div class="overlay"></div>
        <div class="loader">
            <div></div>
            <div></div>
        </div>
    </div>
    <div id="page_loader_leave_partie" class="">
        <div class="overlay"></div>
        <div class="text_loader">
            Chargement en cours ...
        </div>
    </div>
{% endmacro %}